package corba;


/**
* corba/EchoServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* Tuesday, November 15, 2022 10:35:39 AM COT
*/

public interface EchoServiceOperations 
{
  String echo (String x);
  void shutdown ();
} // interface EchoServiceOperations
