package corba;


/**
* corba/EchoService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Echo.idl
* Tuesday, November 15, 2022 10:35:39 AM COT
*/

public interface EchoService extends EchoServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EchoService
